### ISSUE TITLE
Typo in driver forever loop

### ISSUE THREAD

**Issue by j1s1e1** [JoseIuri/UVM-APB_RAL#1]
Jose 

I assume this is a typo in the forever loop in apb_driver:

@(posedge vif.presetn);

If there is only one reset, this hangs up the test bench after the first register write.  I assume you meant to use pclk.

Thanks,

James

**Comment by JoseIuri** [comment]
Yes.

Thats correct. I meant to use pclk. Thanks for the contribution.
